name: Build and deploy Python project to Azure Function App - mohsin-pollz-function

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'  # Set to repo root
  PYTHON_VERSION: '3.12'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      #  Optional: run tests here

      - name: Deploy to Azure Function App via publish profile
        uses: Azure/functions-action@v1
        with:
          app-name: 'mohsin-pollz-function'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9FCD34E5F33C4EC2967F7C17876E73E2 }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
